#=============================================================================
## dark_powered.toml --- dark powered configuration example for SpaceVim
## Copyright (c) 2016-2017 Wang Shidong & Contributors
## Author: Wang Shidong < wsdjeg at 163.com >
## URL: https://spacevim.org
## License: GPLv3
##=============================================================================
#
## All SpaceVim option below [option] section
[options]
  automatic_update = true
  # set spacevim theme. by default colorscheme layer is not loaded,
  # if you want to use more colorscheme, please load the colorscheme
  # layer
  colorscheme = "NeoSolarized"
  colorscheme_bg = "dark"
  # Disable guicolors in basic mode, many terminal do not support 24bit
  # true colors
  enable_guicolors = false
  # Disable statusline separator, if you want to use other value, please
  # install nerd fonts
  buffer_index_type = 0
  enable_cursorline = true
  enable_statusline_mode = true
  enable_tabline_filetype_icon = true
  filemanager = "defx"
  filetree_direction = "left"
  filetype_icon = true
  enable_vimfiler_filetypeicon = true
  relativenumber = false
  statusline_inactive_separator = "arrow"
  statusline_separator = "arrow"
  vimcompatible = true
  enable_neomake = false
  enable_ale = true
  lint_engine = "ale"
  bootstrap_before = "init#before"
  bootstrap_after = "init#after"
  project_rooter_automatically = 0
  autocomplete_method = "deoplete"
  snippet_engine = "neosnippet"
  autocomplete_parens = true
  # left sections of statusline
  statusline_left_sections = [
    "winnr",
    "filename",
    "version control info",
    "minor mode lighters"
  ]
  # right sections of statusline
  statusline_right_sections = [
    "fileformat",
    "major mode",
    "cursorpos",
    "percentage"
  ]
  project_rooter_patterns = ['.SpaceVim.d/']

# Enable autocomplete layer
[[layers]]
  name = "autocomplete"
  auto_completion_enable_snippets_in_popup = true
  auto-completion-return-key-behavior = "complete"
  auto-completion-tab-key-behavior = "smart"

[[layers]]
  name = "lsp"
  filetypes = [
    "rust"
  ]
  [layers.override_cmd]
  rust = ["rls"]

[[layers]]
  name = "shell"
  default_position = "top"
  default_height = 30

[[layers]]
  name = "checkers"

[[layers]]
  name = "colorscheme"

[[layers]]
  name = "ui"

[[layers]]
  name = "git"
  git-plugin = "fugitive"

[[layers]]
  name = "VersionControl"

[[layers]]
  name = "github"

# [[layers]]
#   name = "fzf"

[[layers]]
  name = "denite"

[[layers]]
  name = "tools"

# [[layers]]
#   name = "lang#dockerfile"
# 
# [[layers]]
#   name = "lang#go"
# 
# [[layers]]
#   name = "lang#html"
# 
# [[layers]]
#   name = "lang#javascript"
#   auto_fix = true
#   enable_flow_syntax = true
# 
# [[layers]]
#   name = "lang#sh"
# 
# [[layers]]
#   name = "lang#rust"
#   format-autosave = true
# 
[[layers]]
  name = "lang#typescript"
# 
# [[layers]]
#   name = "lang#vue"
# 
# [[layers]]
#   name = "lang#php"
# 
[[layers]]
  name = "lang#vim"

[[custom_plugins]]
  name = "iberianpig/tig-explorer.vim"

[[custom_plugins]]
  name = "heyyou3/my-todo-vim"

