# use Variables
# ${workspaceFolder}: - /home/your-username/your-project/
# ${workspaceFolderBasename}: - your-project
# ${file}: - /home/your-username/your-project/folder/file.ext
# ${relativeFile}: - folder/file.ext
# ${relativeFileDirname}: - folder/
# ${fileBasename}: - file.ext
# ${fileBasenameNoExtension}: - file
# ${fileDirname}: - /home/your-username/your-project/folder/
# ${fileExtname}: - .ext
# ${lineNumber}: - line number of the cursor
[run_container]
  command = "docker run -it -v ${workspaceFolder}:/home/portfolio -p 3000:3000 -d portfolio_container"
